import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[font.normal]
family = "JetBrains Mono"
style = "Regular"

[font.italic]
family = "JetBrains Mono"
style = "Oblique"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Oblique"
